### ISSUE TITLE
[0][Easy][App] Remove Ollama warning

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pearai-app#337]
Find out why the below warning still pops up, and remove it! We don't use Ollama anymore.

![Image](https://github.com/user-attachments/assets/14c3e10d-244b-4232-8319-dcefe7d583d2)

**Comment by RaxoCoding** [comment]
On it

**Comment by RaxoCoding** [comment]
Problem is in the file `pearai-app/extensions/pearai-submodule/extensions/vscode/src/util/loadAutocompleteModel.ts` the default model is used, since none are defined in the config. The default model is hardcoded to Ollama, which is why this warning pops up. I also noticed you guys have code for the "autocomplete" feature in `core.js` but that code is never called, as the "autocomplete" feature is directly handled in `extensions/vscode/src/extension/VsCodeExtension.ts` with the `ContinueCompletionProvider` class. It seems someone coded everything for the "new" autocomplete I guess (without Ollama) and didn't plug it to vscode.


I can fix this and plug back into `core.js` for the autocomplete. Or if the feature is not ready I can just remove the warning, but would make autocomplete not work.

**Comment by nang-dev** [comment]
it should be undefined. fixed.
